global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'demo'
    static_configs:
      - targets:
        - demo-service-0:10000
        - demo-service-1:10001
        - demo-service-2:10002
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'docker-hub-exporter'
    static_configs:
      - targets: ['docker-hub-exporter:9170']
remote_write:
- url: https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server=demo-prom
  authorization:
    credentials: NR_LICENSE_KEY

